export const PostData = [
  {
    id: 1,
    desc: "This is my first post :)",
    photo: "person1.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 9,
  },
  {
    id: 2,
    desc: "Had alot of fun this summer",
    photo: "person2.jpg",
    date: "5 days ago",
    userId: 5,
    like: 100,
    comment: 10,
  },
  {
    id: 3,
    desc: "Don't let yourself dry. Keep yourself moisturized with our product",
    photo: "advertisement.jpg",
    date: "5 hour ago",
    userId: 2,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "My look yesterday. Tell me what you think about it.",
    photo: "person3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 5,
    desc: "Had alot of fun with my friends at the all night party. Looking forward to the next one.",
    photo: "person4.jpg",
    date: "15 days ago",
    userId: 4,
    like: 61,
    comment: 2,
  },
  {
    id: 6,
    desc: "I saw and I conquered",
    photo: "person5.jpg",
    date: "5 hours ago",
    userId: 2,
    like: 21,
    comment: 2,
  },
  {
    id: 7,
    desc: "Original shoes. Durable for the current weather condition.",
    photo: "person3.jpg",
    date: "10 hours ago",
    userId: 1,
    like: 61,
    comment: 2,
  },
];

export const Users = [
  {
    id: 1,
    userId: 1,
    username: "Phinehas Sersah",
    profilePicture: "person1.jpg",
  },
  {
    id: 2,
    userId: 2,
    username: "Justice Ajah",
    profilePicture: "person2.jpg",
  },
  {
    id: 3,
    userId: 3,
    username: "Kwabena Dwamena",
    profilePicture: "person3.jpg",
  },
  {
    id: 4,
    userId: 4,
    username: "Victor Aremu",
    profilePicture: "person4.jpg",
  },
  {
    id: 5,
    userId: 5,
    username: "Michael Acheampong",
    profilePicture: "person5.jpg",
  },
];
